name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        
      - name: Deploy to Render
        # Trigger Render deploy hook
        run: |
          echo "Deploying application to Render"
          # Replace YOUR_RENDER_DEPLOY_HOOK_URL with your actual Render deploy hook URL
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
